permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Liu Kang
  email: liukang325@qq.com
  link: http://lk.link-pub.cn
  weibo: http://weibo.com/234100789
  github: http://github.com/liukang325
  music: 
  linkedin: 

# 站点信息
title: 阳光柠檬的博客
description: My personal blog
url: lk.link-pub.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/me.jpg
favicon: /public/img/me.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: lk.link-pub.cn

# disqus 设置
disqus:
  shortname: liukang325

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Markdown

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档