# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hello，阳光柠檬！
brief-intro: 养成记录笔记的好习惯
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liukang325.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
github_username:  liukang325
email: liukang325@qq.com
weibo_username: liukang325
zhihu_username: liukang325

description_footer:

#gitment
comment_gitment_repo: liukang325.github.io
comment_gitment_clientId: 
comment_gitment_clientSecret: 


# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
# baidu_tongji_id: e5a35e62751b1f5305cfc174a374fd4d
# google_analytics_id: UA-116772911-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
